<AgendaWidget>:
    do_default_tab: False
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            size: self.size
            pos: self.pos

#january
    TabbedPanelItem:
        text: "jan"
        id: jan_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"     
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: jan_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: 24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jan_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1

#february
    TabbedPanelItem:
        text: "feb"
        id: feb_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: feb_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: feb_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#march
    TabbedPanelItem:
        text: "mar"
        id: mar_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: mar_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: mar_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#april
    TabbedPanelItem:
        text: "apr"
        id: apr_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: apr_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: apr_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#may    
    TabbedPanelItem:
        text: "may"
        id: may_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: may_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: may_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#june
    TabbedPanelItem:
        text: "jun"
        id: jun_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: jun_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jun_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#july    
    TabbedPanelItem:
        text: "jul"
        id: jul_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: jul_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: jul_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#aug   
    TabbedPanelItem:
        text: "aug"
        id: aug_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: aug_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: aug_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#sept
    TabbedPanelItem:
        text: "sept"
        id: sept_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: sept_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: sept_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#oct    
    TabbedPanelItem:
        text: "oct"
        id: oct_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: oct_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: oct_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#nov    
    TabbedPanelItem:
        text: "nov"
        id: nov_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: nov_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: nov_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#dec    
    TabbedPanelItem:
        text: "dec"
        id: dec_tab
        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    id: dec_1
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_2
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_3
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_4
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_5
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_6
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_7
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_8
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_9
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_10
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_11
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_12
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_13
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_14
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_15
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_16
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_17
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_18
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_19
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_20
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_21
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_22
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_23
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_24
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_25
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_26
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_27
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_28
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_29
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_30
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_31
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_32
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_33
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_34
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    id: dec_35
                    font_size: 10
                    background_normal: ""         
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1