<AgendaWidget>:
    do_default_tab: False
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            size: self.size
            pos: self.pos

#january
    TabbedPanelItem:
        text: "jan"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"     
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1

#february
    TabbedPanelItem:
        text: "fev"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5


                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#march
    TabbedPanelItem:
        text: "march"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5


                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#april
    TabbedPanelItem:
        text: "april"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#may    
    TabbedPanelItem:
        text: "may"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#june
    TabbedPanelItem:
        text: "june"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#july    
    TabbedPanelItem:
        text: "july"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#aug   
    TabbedPanelItem:
        text: "aug"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#sept
    TabbedPanelItem:
        text: "sept"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#oct    
    TabbedPanelItem:
        text: "oct"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#nov    
    TabbedPanelItem:
        text: "nov"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
    
#dec    
    TabbedPanelItem:
        text: "dec"

        BoxLayout:
            orientation: 'vertical'

            GridLayout:
                cols: 7
                size_hint_y: None
                height: 30  

                Button:
                    text: "Mon"
                    font_size: 10
                Button:
                    text: "Tue"
                    font_size: 10
                Button:
                    text: "Wed"
                    font_size: 10
                Button:
                    text: "Thu"
                    font_size: 10
                Button:
                    text: "Fri"
                    font_size: 10
                Button:
                    text: "Sat"
                    font_size: 10
                Button:
                    text: "Sun"
                    font_size: 10

            GridLayout:
                cols: 7
                rows: 5   
                spacing: 5
                padding: 5

                Button:
                    text: "1"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "2"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "3"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "4"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "5"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "6"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "7"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "8"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "9"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "10"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "11"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "12"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "13"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "14"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "15"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "16"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "17"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "18"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "19"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "20"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "21"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "22"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "23"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "24"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "25"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "26"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "27"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "28"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "29"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "30"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "31"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "32"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "33"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "34"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1
                Button:
                    text: "35"
                    font_size: 10
                    background_normal: ""        
                    background_color: 1, 1, 1, 1 
                    color: 0, 0, 0, 1